apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: epharmacy

data:
  DB_NAME: "payment_db"
  DB_URL: "jdbc:mysql://payment-db:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  EUREKA: "http://eureka:8761/eureka/"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: "http://192.168.49.2:30081"  
