apiVersion: v1
kind: Secret
metadata:
  name: medicine-service-secret
  namespace: epharmacy    
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  JWT_SECRET: "YEfa5b24N2ILGw1stBVt3277MuNY2Ajr58VOYWGeG7Y=" 
