apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: epharmacy
spec:
  selector:
    app: mysql        # <-- must match the actual label on your mysql pod/deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
