

services:
  eureka:
    build:
      context: ./pharmacy-eureka-server
      dockerfile: Dockerfile  
    container_name: pharmacy-eureka
    ports:
      - "8761:8761"  
    environment:
      SERVER_PORT: 8761
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s     
  
  redis:
    image: redis:alpine
    container_name: pharmacy-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s




  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - user-db-data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 

  medicine-db:
    image: mysql:8.0
    container_name: medicine-db
    environment:
      MYSQL_DATABASE: ${MEDICINE_DB_NAME}
      MYSQL_USER: ${MEDICINE_DB_USER}
      MYSQL_PASSWORD: ${MEDICINE_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - medicine-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s     


  cart-db:
    image: mysql:8.0
    container_name: cart-db
    environment:
      MYSQL_DATABASE: ${CART_DB_NAME}
      MYSQL_USER: ${CART_DB_USER}
      MYSQL_PASSWORD: ${CART_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - cart-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s      


  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_DATABASE: ${ORDER_DB_NAME}
      MYSQL_USER: ${ORDER_DB_USER}
      MYSQL_PASSWORD: ${ORDER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - order-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    environment:
      MYSQL_DATABASE: ${PAYMENT_DB_NAME}
      MYSQL_USER: ${PAYMENT_DB_USER}
      MYSQL_PASSWORD: ${PAYMENT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - payment-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



  
  user-api:
    build:
      context: ./pharmacy-user-service
      dockerfile: Dockerfile
    container_name: pharmacy-user-api 
    ports:
      - "8081:8081"   
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/${USER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/   
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:
        condition: service_healthy 
      user-db:
        condition: service_healthy



  medicine-api:
    build:
      context: ./pharmacy-medicine-service
      dockerfile: Dockerfile
    container_name: pharmacy-medicine-api
    ports:
      - "8082:8082"    
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://medicine-db:3306/${MEDICINE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${MEDICINE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MEDICINE_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/  
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:
        condition: service_healthy 
      medicine-db:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  cart-api:
    build:
      context: ./pharmacy-cart-service
      dockerfile: Dockerfile
    container_name: pharmacy-cart-api
    ports:
      - "8083:8083"   
    environment:
      SERVER_PORT: 8083 
      SPRING_DATASOURCE_URL: jdbc:mysql://cart-db:3306/${CART_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${CART_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${CART_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:
        condition: service_healthy 
      cart-db:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  order-api:
    build:
      context: ./pharmacy-order-service
      dockerfile: Dockerfile
    container_name: pharmacy-order-api
    ports:
      - "8084:8084"   
    environment:
      SERVER_PORT: 8084 
      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/   
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:
        condition: service_healthy  
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  payment-api:
    build:
      context: ./pharmacy-payment-service
      dockerfile: Dockerfile
    container_name: pharmacy-payment-api
    ports:
      - "8085:8085"    
    environment:
      SERVER_PORT: 8085 
      SPRING_DATASOURCE_URL: jdbc:mysql://payment-db:3306/${PAYMENT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PAYMENT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/   
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:  
        condition: service_healthy 
      payment-db:
        condition: service_healthy     
          
  api-gateway:
    build:
      context: ./pharmacy-api-gateway-service
      dockerfile: Dockerfile
    container_name: pharmacy-api-gateway
    ports:
      - "8080:8080"  
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/  
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka:
        condition: service_healthy 
  
  
  web:
    build:
      context: ./epharmacy-frontend
      dockerfile: Dockerfile
      args:
        VITE_GATEWAY_URL: ${API_GATEWAY_URL}  
    container_name: pharmacy-web
    ports:
      - "5173:80"
    depends_on:
      - api-gateway    

volumes:
  user-db-data:
  medicine-db-data:
  cart-db-data:
  order-db-data:
  payment-db-data:
         
        
    
