spring:
  application:
    name: pharmacy-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://PHARMACY-USER-SERVICE
              predicates:
                - Path=/customer/**

            - id: medicine-service
              uri: lb://PHARMACY-MEDICINE-SERVICE
              predicates:
                - Path=/medicine/**

            - id: cart-service
              uri: lb://PHARMACY-CART-SERVICE
              predicates:
                - Path=/cart/**

            - id: order-service
              uri: lb://PHARMACY-ORDER-SERVICE
              predicates:
                - Path=/order/**

server:
  port: 8080