apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: epharmacy

data:
  DB_NAME: "cart_db"
  DB_URL: "jdbc:mysql://cart-db:3306/cart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"  
  EUREKA: "http://eureka:8761/eureka/"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: "http://192.168.49.2:30081"  
