apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: epharmacy

data:
  EUREKA: "http://eureka:8761/eureka/"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: "http://192.168.49.2:30081,http://localhost:5173"  
