apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-gateway-service
 namespace: epharmacy
 labels:
   app: api-gateway-service
spec:
 replicas: 1
 selector:
   matchLabels:
     app: api-gateway-service
 template:
   metadata:
     labels:
       app: api-gateway-service
   spec:
     containers:
       - name: api-gateway-service
         image: vinayacharya07/pharmacy-api-gateway:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8080
         env:
           - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
             value: "http://eureka:8761/eureka"
           - name: REDIS_HOST
             valueFrom:
               configMapKeyRef:
                 name: cart-service-config
                 key: REDIS_HOST
           - name: REDIS_PORT
             valueFrom:
               configMapKeyRef:
                 name: cart-service-config
                 key: REDIS_PORT

           - name: CORS_ALLOWED_ORIGINS
             valueFrom:
               configMapKeyRef:
                 name: api-gateway-config
                 key: CORS_ALLOWED_ORIGINS
