apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: epharmacy
spec:
  type: ClusterIP
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
        

