spring:
  application:
    name: pharmacy-user-service

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
  instance:
    prefer-ip-address: true   
server:
  port: 8081
  
jwt:
  secret: ${JWT_SECRET} 
  
