spring:
  application:
    name: pharmacy-user-service

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8081
  
jwt:
  secret: ${JWT_SECRET} 
  
