apiVersion: apps/v1
kind: Deployment
metadata:
 name: eureka
 namespace: epharmacy  
 labels:
   app: eureka
spec:
 replicas: 1
 selector:
   matchLabels:
     app: eureka
 template:
   metadata:
     labels:
       app: eureka
   spec:
     containers:
     - name: eureka
       image: vinayacharya07/pharmacy-eureka:latest 
       imagePullPolicy: Always  
       ports:
       - containerPort: 8761
