apiVersion: v1
kind: Secret

metadata:
  name: cart-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secrets.cart.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.cart.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.cart.JWT_SECRET | quote }}
