apiVersion: v1
kind: Service

metadata:
  name: eureka
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: eureka

  ports:
    - port: {{ .Values.services.eureka.port }}
      targetPort: {{ .Values.services.eureka.port }}
      protocol: TCP
