apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: "{{ .Values.images.gateway.repository }}:{{ .Values.images.gateway.tag }}"
          imagePullPolicy: {{ .Values.images.gateway.pullPolicy }}
          envFrom:
            - configMapRef:
                name: api-gateway-config
          ports:
            - containerPort: {{ .Values.services.gateway.port }}
