apiVersion: v1
kind: ConfigMap

metadata:
  name: medicine-service-config
  namespace: {{ .Values.namespace }}

data:
  CORS_ALLOWED_ORIGINS: {{ .Values.app.corsAllowedOrigins | quote }}
  DB_NAME: "medicine_db"
  DB_URL: "jdbc:mysql://medicine-db:3306/medicine_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  EUREKA: "http://eureka:8761/eureka/"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
