apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
  storageClassName: {{ .Values.mysql.storage.storageClass }}
