apiVersion: v1
kind: Secret

metadata:
  name: payment-service-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secrets.payment.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.payment.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.payment.JWT_SECRET | quote }}
