apiVersion: v1
kind: ConfigMap

metadata:
  name: user-service-config
  namespace: {{ .Values.namespace }}

data:
  CORS_ALLOWED_ORIGINS: {{ .Values.app.corsAllowedOrigins | quote }}
  DB_NAME: "user_db"
  DB_URL: "jdbc:mysql://user-db:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  EUREKA: "http://eureka:8761/eureka/"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
