apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: {{ .Values.services.user.port }}
      targetPort: {{ .Values.services.user.port }}
      protocol: TCP
