apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: epharmacy
  
data:
  DB_NAME: "customer_db"
  DB_URL: "jdbc:mysql://user-db:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"  
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"  
  EUREKA: "http://eureka:8761/eureka/"  
  CORS_ALLOWED_ORIGINS: "http://192.168.49.2:30081"   
