spring:
  application:
    name: pharmacy-medicine-service

  datasource:
    url: jdbc:mysql://mysql:3306/medicine_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis    
    redis:
      time-to-live: 10m

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}
